name: Create new project tasks when latest.7z updated
on:
  push:
    branches:
      - main
    paths:
      - 'latest.7z'
jobs:
  create-item:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get file contents
        run: echo "latest.7z=$(cat latest.7z)"
      - name: Create item in task
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN}}" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "Update tasks when CBDB SQLite updated",
              "body": "Please update API, biog_ref, calculate index year by Access, update index year to API + inputting system, send data dump to ChineseAll, send date to CBDB Line.",
            }' \
            https://api.github.com/orgs/cbdb-project/projects/3/items
